name: CD Workflow

on:
  push: 
    branches:
      - main
      
jobs:
  cd-test-deploy:
        name: CD deploy Test
        runs-on: ubuntu-latest
        environment: test
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'
          - name: install Databricks CLI
            run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          - name: Install Dependencies
            run: |
                  pip install --upgrade pip
                  pip install setuptools wheel
          - name: configure Databricks
            run: |
                  cat <<EOF > ~/.databrickscfg
                  [TEST]
                  host=https://dbc-17cbe7de-090a.cloud.databricks.com/
                  token=${{secrets.TOKEN}}
                  EOF
          - name: Deploy to TEST
            run: |
                  databricks bundle deploy -t test --profile TEST

  cd-prod-deploy:
          name: Deploy to prod
          needs: cd-test-deploy
          runs-on: ubuntu-latest
          environment: prod
          steps:
             - name: Checkout code
               uses: actions/checkout@v3
             - name: Set up python
               uses: actions/setup-python@v4
               with:
                 python-version: '3.11'
             - name: install Databricks CLI
               run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
             - name: Install Dependencies
               run: |
                  pip install --upgrade pip
                  pip install setuptools wheel
             - name: configure Databricks
               run: |
                  cat <<EOF > ~/.databrickscfg
                  [PROD]
                  host=https://dbc-8fc8b6b2-f985.cloud.databricks.com
                  token=${{secrets.TOKEN}}
                  EOF
             - name: Deploy to TEST
               run: |
                  databricks bundle deploy -t prod --profile PROD
          

      
